from cassandra.cluster import Cluster, ExecutionProfile,EXEC_PROFILE_DEFAULT
from cassandra.auth import PlainTextAuthProvider
import json
import pandas as pd
from cassandra.query import BatchStatement
import matplotlib.pyplot as plt

# Creating a connection
cloud_config= {
  'secure_connect_bundle': 'your-secure-connect.zip'
}

# This token JSON file is autogenerated when you download your token, 
# if yours is different update the file name below
with open("ADD_YOUR_TOKEN_FILE.json") as f:
    secrets = json.load(f)

CLIENT_ID = secrets["clientId"]
CLIENT_SECRET = secrets["secret"]

auth_provider = PlainTextAuthProvider(CLIENT_ID, CLIENT_SECRET)
# Defining a custom execution profile with a longer timeout
profile=ExecutionProfile(request_timeout=300)
cluster = Cluster(cloud=cloud_config, auth_provider=auth_provider,execution_profiles={EXEC_PROFILE_DEFAULT:profile})
session = cluster.connect('finalproject')

row = session.execute("select release_version from system.local").one()
if row:
  print(row[0])
else:
  print("An error occurred.")

# Creating bronze layer table
session.execute("""
  CREATE TABLE IF NOT EXISTS finalproject.bronzelayer(
             houseid text PRIMARY KEY,
              housetype text,
                salestype text,
                yearbuild int,
                purchaseprice int,
                nrooms int,
                sqm int,
                sqmprice float,
                zipcode text,
                city text,
                area text,
                region text
                )""") 

# IMPORTANT: I used dsbulk to load the data into Bronze layer table

# Checking Bronze Layer table
# Counting number of rows in Bronze Layer table
query1="SELECT * FROM bronzelayer"
rows1=session.execute(query1)
df1=pd.DataFrame(rows1)
print('Number of rows and columns respectively in Bronze Layer Table: ',df1.shape)  # We confirm 100000 rows and 12 columns

# Checking if bronze layer table was created correctly
print(df1.head())

# CLEANING DATA
print(df1.dtypes) #Checking current data types

# Change type of data and looking for null values
df1['purchaseprice']=df1['purchaseprice'].astype(float)
nullCounts=df1.isnull().sum()
print(nullCounts) # We see some null values in "city"
print(df1.dtypes)

# Filling null values of "city" with mode, according to the "area"
df1['city']=df1.groupby('area')['city'].transform(lambda x: x.fillna(x.mode()[0] if not x.mode().empty else 'Unknown'))

# Checking if 'city' has any null value
print(df1['city'].isnull().sum())

df_silver = df1.copy()

# Converting df_silver to a new CSV file because I will load that into the Silver Layer table through dsbulk
df_silver.to_csv('silverlayer.csv',index=False)

# Creating Silver Layer Table
session.execute("""
  CREATE TABLE IF NOT EXISTS finalproject.silverlayer(
             houseid text,
              housetype text,
                salestype text,
                yearbuild int,
                purchaseprice double,
                nrooms int,
                sqm int,
                sqmprice double,
                zipcode text,
                city text,
                area text,
                region text,
                PRIMARY KEY ((houseid),zipcode)
                )""") 

# IMPORTANT: I loaded the data into Silver Layer Table through dsbulk

# Checking Silver Layer table
# Counting number of rows in Silver Layer table
query1="SELECT * FROM silverlayer"
rows1=session.execute(query1)
df1=pd.DataFrame(rows1)
print('Number of rows and columns respectively in Silver Layer Table: ',df1.shape)  # We confirm 100000 rows and 12 columns

# Checking if Silver Layer table was created correctly
print(df1.head()) #Everything looks good

# Aggregating data for the Gold Layer Table
df_gold=df1.groupby(['region','city']).agg({
  'purchaseprice':['mean','min','max'],
  'houseid':'count',
  'nrooms':'mean',
  'sqm':'mean'
})
df_gold.columns=['_'.join(col).strip() for col in df_gold.columns]

df_gold=df_gold.rename(columns={
   'purchaseprice_mean':'avg_purchaseprice',
   'purchaseprice_min':'min_purchaseprice',
   'purchaseprice_max':'max_purchaseprice',
   'houseid_count':'number_houses',
   'nrooms_mean':'avg_rooms',
   'sqm_mean':'avg_sqm'
}).reset_index()

# Checking if df_gold was created correctly
print(df_gold.head())  #It looks good

# Converting df_gold to csv file to load into Gold Layer Table through dsbulk
df_gold.to_csv('goldlayer.csv',index=False)

# Creating Gold Layer Table
session.execute("""
  CREATE TABLE IF NOT EXISTS finalproject.goldlayer(
                region text,
                city text,
                avg_purchaseprice double,
                min_purchaseprice double,
                max_purchaseprice double,
                number_houses int,
                avg_rooms double,
                avg_sqm double,
                PRIMARY KEY ((region),city)
                )""")

# IMPORTANT: I loaded the data into Gold Layer Table through dsbulk

# Checking Gold Layer table
# Counting number of rows in Gold Layer table
query1="SELECT * FROM goldlayer"
rows1=session.execute(query1)
df1=pd.DataFrame(rows1)
print('Number of rows and columns respectively in Gold Layer Table: ',df1.shape)

# Checking if Gold Layer table was created correctly
print(df1.head())

# Displaying graphs using Gold Layer Table
#Barplot of number of houses by region
regionC=df1.groupby('region')['number_houses'].sum().reset_index()
plt.figure(figsize=(12,9))
plt.bar(regionC['region'],regionC['number_houses'],color='red',edgecolor='black')
plt.title('Number of Houses by Region')
plt.xlabel('Region')
plt.ylabel('Number of houses')
plt.show()

# Boxplot of average purchase prices accross the regions
plt.figure(figsize=(12,9))
plt.boxplot([df1[df1['region']==region]['avg_purchaseprice'] for region in df1['region'].unique()],tick_labels=df1['region'].unique())
plt.title('Average Purchase Prices Accross the Regions')
plt.xlabel('Region')
plt.ylabel('Avegare Purchase Price')
plt.show()

# Pie chart of percentage of houses by region
df1_grouped=df1.groupby('region')['number_houses'].sum().reset_index()
labels=df1_grouped['region']
sizes=df1_grouped['number_houses']
plt.figure(figsize=(10,10))
plt.pie(sizes,labels=labels,autopct='%1.1f%%')
plt.title('Percentages of Houses by Region')
plt.show()